name: asunode_iot
description: "ESP IoT Monitoring Dashboard with Neumorphic UI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.0
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  window_manager: ^0.3.8
  google_fonts: ^6.1.0
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
